### OpenAI Source
openai_source: "azure"

### inference model
inference_model_name_or_path: Taide/Llama-3.1-TAIDE-LX-8B-Chat 
inference_mode: local
cot: false

### checker model
checker_model_name_or_path: Qwen/Qwen2.5-32B-Instruct
check_mode: local

### translation model
translation_model_name_or_path: gpt-4o-mini
translation_mode: api
transation_templates_name: proper_nouns
source_lang: en
target_lang: zh-tw

### source dataset
task: mbpp_test  
task_dir: evaluation_data
lang: en
n_shot: 3
benchmark_mode: code
pipeline: diff
batch_size: 4

### reference dataset, split will use 'test' don't specify
# ref_task: mmlu

### output
save_dir: score/main_pipeline/mbpp/zh-tw

### VLLM 
vllm_maxlen: 8192
vllm_max_concurrency: 30
max_new_tokens: 2048
dtype: float32
### debug
# testing_size: 2
record_all: true
# print_param_status: false