### inference model
inference_model_name_or_path: google/gemma-2-9b-it
inference_mode: local
openai_source: "azure"
cot: true

### checker model
checker_model_name_or_path: Qwen/Qwen2.5-32B-Instruct
check_mode: local

### dataset
task: gpqa_test  
task_dir: evaluation_data
template: fewshot
lang: en
n_shot: 5

### output
save_dir: score/gpqa/gemma-2-9b-it-cot

### eval
vllm_maxlen: 8192
