################
# 必需要更改的：
# task_dir: en -> zh, ko, ...
# lang: en -> zh, ko, ...
################
### OpenAI Source
openai_source: "azure"

### inference model
inference_model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
inference_mode: local
cot: false

### checker model
checker_model_name_or_path: Qwen/Qwen2.5-32B-Instruct
check_mode: local

### source dataset
task: huatuo_test
task_dir: evaluation_data/huatuo/zh
lang: zh
n_shot: 5
benchmark_mode: opqa
pipeline: same

### output
save_dir: score/huatuo_test/zh

### VLLM 
vllm_maxlen: 10240
vllm_max_concurrency: 30
max_new_tokens: 2048
dtype: float16
### debug
testing_size: 3
record_all: true
# print_param_status: false