### OpenAI Source
openai_source: "azure"

### inference model
inference_model_name_or_path: Qwen/Qwen3-30B-A3B-Instruct-2507
inference_mode: endpoint
inference_model_endpoint: http://localhost:8080/v1

### checker model
checker_model_name_or_path: Qwen/Qwen3-30B-A3B-Instruct-2507
check_mode: endpoint
checker_model_endpoint: http://localhost:8080/v1

### source dataset
task: huatuo_test
task_dir: evaluation_data/huatuo/zh
lang: zh
n_shot: 5
benchmark_mode: opqa
pipeline: same
cot: false

### output
save_dir: score/test_endpoint

### VLLM 
vllm_maxlen: 10240
vllm_max_concurrency: 30
max_new_tokens: 2048
dtype: float16
### debug
testing_size: 3
record_all: true
# print_param_status: false